### PR TITLE
Fix/editing badge deletes competencies

### LINKED ISSUE #359: esco competencies disappear when uploading a new badge image
the esco competencies disappear when you edit an existing competency badge (= upload a new badge image). it is also not possible to add the deleted competencies again because they are not saved at all or only partially during the edit+save process.

### PR DESCRIPTION
**Pull request by jona159**
Fixes #359

### CODE REVIEW

File: src/app/issuer/components/badgeclass-edit-form/badgeclass-edit-form.component.ts [hunk 1]
```diff
@@ -713,7 +713,7 @@ export class BadgeClassEditFormComponent extends BaseAuthenticatedRoutableCompon
 		try {
 			if (this.badgeClassForm.rawControl.controls.badge_category.value === 'competency') {
 				this.badgeClassForm.controls.competencies.rawControls.forEach((control, i) => {
-					if (control.untouched) {
+					if (control.untouched && control.status === 'INVALID') {
```
Comment (timber-they) [inline src/app/issuer/components/badgeclass-edit-form/badgeclass-edit-form.component.ts:716]: A comment indicating why we want to remove competencies in this case would be nice.

**Review by timber-they — CHANGES_REQUESTED** [review]

**Review by timber-they — APPROVED** [review]
